return {
  "airblade/vim-gitgutter",
  event = "VeryLazy",
  config = function()
    -- Deprioritize gitgutter signs over any other that has the default of 10.
    -- Example vim.diagnostics generated by LSP.
    vim.g.gitgutter_sign_priority = 5
  end
}
